import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TanstackProvider from '@/providers/TanstackProvider';
import { SessionProvider } from 'next-auth/react';
import { ThemeProviders } from '@/providers/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders>
          <SessionProvider>
            <TanstackProvider>
              <div>{children}</div>
            </TanstackProvider>
          </SessionProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
